[package]
name = "cyrel"
version = "0.1.0"
authors = ["alyrow"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
pbkdf2 = "0.7"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json", "databases", "helmet", "diesel_sqlite_pool", "handlebars_templates"]